### ISSUE TITLE
composer 组件开发

### ISSUE THREAD

**Issue by rayjun** [overtrue/laravel-shopping-cart#1]
在composer.json里面并没有看到你 require laravel 框架，但为何在代码里面却用到了laravel的组件。
另外，composer开发有相关的资料么，求推荐。我是雷俊，上回的线下聚会我也在。

**Comment by overtrue** [comment]
1. 这个库本来就是只能在 Laravel 下用的，所以没有写依赖框架
2. composer 主要资料就是官方文档了：https://getcomposer.org ([中文](http://www.phpcomposer.com/))
