### ISSUE TITLE
Update does not work during adding of the same item if quantity is different

### ISSUE THREAD

**Issue by N-M** [overtrue/laravel-shopping-cart#2]
Update does not work properly during adding of the same item if quantity is different
```php
Cart::add(37, 'Item name', 5, 100.00, ['color' => 'red', 'size' => 'M']);
Cart::add(37, 'Item name', 1, 100.00, ['color' => 'red', 'size' => 'M']);
Cart::add(37, 'Item name', 5, 100.00, ['color' => 'red', 'size' => 'M']);
```
![image](https://cloud.githubusercontent.com/assets/781417/9258309/010936b4-41fb-11e5-9b46-82c508289644.png)

**Comment by overtrue** [comment]
@N-M Thank you, I will check it.

**Comment by overtrue** [comment]
@N-M Hi, I have fixed it. please update to version: 1.0.1, Thanks.
