### ISSUE TITLE
composer install error

### ISSUE THREAD

**Issue by shjchen** [overtrue/laravel-shopping-cart#4]
两种安装方式都存在错误
一  `composer require "overtrue/laravel-shopping-cart:1.0.*" `
会提示 如下错误。 但是我本地已经安装了更高级的log-viewer 版本
![image](https://cloud.githubusercontent.com/assets/9166101/14769189/05f65c34-0a86-11e6-9e65-9cedadf1e33d.png)

二  更新composer.json 文件后，进行composer update 操作
会出现如下错误
![image](https://cloud.githubusercontent.com/assets/9166101/14769199/37f75df0-0a86-11e6-894d-4bf2621bd67b.png)

尝试多次后仍无法解决此问题。

第二种方式出现的symfony问题可能是官方的。

**Comment by overtrue** [comment]
@shjchen 我的包没有依赖log-viewer 所以问题1是你自己的配置问题，问题2也同样报的是symfony的问题我并没有依赖该包。

**Comment by shjchen** [comment]
恩，已经自己解决掉了。

就是因为国内镜像https无法更新composer.json，导致本地缓存的都是一些老版本的包，所以这些包报错了。
