### ISSUE TITLE
文档中使用静态方法调用有误吧

### ISSUE THREAD

**Issue by moore0903** [overtrue/laravel-shopping-cart#5]
安神,你文档中写的使用静态方式调用是错误的吧,要先new一个对象,方法中没有加静态

**Comment by overtrue** [comment]
请学会使用 Laravel Facade，以及仔细看文档哦：https://github.com/overtrue/laravel-shopping-cart#installation

**Comment by moore0903** [comment]
谢谢,又学到了一些,但是还是有个地方不明白,如果我在控制器中直接使用Cart::add(),这个时候导入的命名空间是use Overtrue\LaravelShoppingCart\Cart; 这个,这个如果用静态方式调用的话会出现错误.除非我不导入命名空间,直接使用\Cart:add()就没有问题.
在app.php 中
![image](https://cloud.githubusercontent.com/assets/20037570/24150908/28a917a2-0e82-11e7-8fdd-0691ce0cf47e.png)也加了.

**Comment by overtrue** [comment]
额，我都建议你去学一下命名空间了，这里一共有两个类：

```php
use Overtrue\LaravelShoppingCart\Cart;
use Overtrue\LaravelShoppingCart\Facade;
```

上一个是最后业务使用的类，并非静态，后者 `Overtrue\LaravelShoppingCart\Facade` 是上一个 `Overtrue\LaravelShoppingCart\Cart` 类的**外观**类，静态代理，而在 Laravel 配置 `config/app.php` 里配置 `aliases`：

```php
'Cart' => Overtrue\LaravelShoppingCart\Facade::class,
```

这行的作用是在根命名空间 `\` 下创建了别名类 `\Cart` 指向 `\Overtrue\LaravelShoppingCart\Facade`, 所以使用 `use Cart` 或者  `\Cart` 都是使用 `\Overtrue\LaravelShoppingCart\Facade`。

请分清楚这里的  `\Cart` 与 `\Overtrue\LaravelShoppingCart\Cart` 的区别，它俩完全是两个不同的东西，一个是**根空间**下的 `Cart`，另一个是 **根空间** 下的 `Overtrue\LaravelShoppingCart\Cart` , 所以并没有 "除非我不导入命名空间" 这样的说法存在。

类别名：http://php.net/manual/en/function.class-alias.php
命名空间：http://php.net/manual/zh/language.namespaces.php

**Comment by moore0903** [comment]
哦哦,好的,谢谢啊,基础较差,感谢你的耐心讲解
