### ISSUE TITLE
Undefined type

### ISSUE THREAD

**Issue by Abualibek** [overtrue/laravel-shopping-cart#61]
In my CartController.php I am pasting "use Overtrue\LaravelShoppingCart\ShoppingCart;" and 

public function index()
    {
        return ShoppingCart::content();
    }

But the error I am getting: "Undefined type 'Overtrue\LaravelShoppingCart\ShoppingCart'.intelephense(1009)"

**Comment by overtrue** [comment]
It seems like related the vscode plugin: bmewburn/vscode-intelephense
https://github.com/bmewburn/vscode-intelephense/issues/1035
